import React,{useEffect,useRef,useState} from 'react';
import {Alert,StyleSheet,Text,View} from 'react-native';
import {Button,Card,theme,api,getToken} from '@commerce/mobile-core';
import {mediaDevices,RTCPeerConnection,RTCSessionDescription,RTCIceCandidate} from 'react-native-webrtc';
const API=process.env.EXPO_PUBLIC_API_BASE_URL||(__DEV__?'http://10.0.2.2:4000':'');
if(!API) throw new Error('EXPO_PUBLIC_API_BASE_URL_REQUIRED');
if(!__DEV__ && !/^https:\/\//i.test(API)) throw new Error('PRODUCTION_API_MUST_USE_HTTPS');
type Props={callId:string;onEnded:()=>void};
export default function CallPanel({callId,onEnded}:Props){const pc=useRef<any>(null),ws=useRef<WebSocket|null>(null),stream=useRef<any>(null);const [status,setStatus]=useState('Connecting…');const [muted,setMuted]=useState(false);useEffect(()=>{let alive=true;(async()=>{try{const token=await getToken();if(!token)throw new Error('SESSION_REQUIRED');const conn=new RTCPeerConnection({iceServers:[{urls:process.env.EXPO_PUBLIC_STUN_URL||'stun:stun.l.google.com:19302'},...(process.env.EXPO_PUBLIC_TURN_URL?[{urls:process.env.EXPO_PUBLIC_TURN_URL,username:process.env.EXPO_PUBLIC_TURN_USERNAME||'',credential:process.env.EXPO_PUBLIC_TURN_CREDENTIAL||''}]:[])]});pc.current=conn;conn.onicecandidate=(e:any)=>{if(e.candidate)ws.current?.send(JSON.stringify({type:'call.signal',callId,data:{kind:'candidate',candidate:e.candidate}}))};conn.onconnectionstatechange=()=>setStatus(conn.connectionState==='connected'?'Connected':conn.connectionState);stream.current=await mediaDevices.getUserMedia({audio:true,video:false});stream.current.getTracks().forEach((t:any)=>conn.addTrack(t,stream.current));const socket=new WebSocket(API.replace(/^https?/,API.startsWith('https://')?'wss':'ws')+`/realtime?token=${encodeURIComponent(token)}`);ws.current=socket;socket.onopen=()=>setStatus('Waiting for customer media…');socket.onmessage=async(e)=>{const msg=JSON.parse(e.data);if(msg.callId!==callId||msg.type!=='call.signal')return;const d=msg.data||{};if(d.kind==='description'){if(d.description?.type==='offer'){await conn.setRemoteDescription(new RTCSessionDescription(d.description));const answer=await conn.createAnswer({});await conn.setLocalDescription(answer);socket.send(JSON.stringify({type:'call.signal',callId,data:{kind:'description',description:answer}}));}else if(d.description?.type==='answer'){await conn.setRemoteDescription(new RTCSessionDescription(d.description));}}else if(d.kind==='candidate'&&d.candidate){try{await conn.addIceCandidate(new RTCIceCandidate(d.candidate));}catch{}}if(msg.type==='call.end')onEnded()};socket.onerror=()=>setStatus('Realtime error');}catch(e:any){if(alive)Alert.alert('Call',e.message||'Unable to start call');onEnded()}})();return()=>{alive=false;try{ws.current?.close()}catch{};try{stream.current?.getTracks()?.forEach((t:any)=>t.stop())}catch{};try{pc.current?.close()}catch{}}},[callId,onEnded]);const end=async()=>{try{await api(API,`/v1/admin/calls/${callId}/status`,{method:'POST',body:JSON.stringify({status:'ENDED'})})}catch{};onEnded()};const toggle=()=>{const ts=stream.current?.getAudioTracks?.()||[];const next=!muted;ts.forEach((t:any)=>t.enabled=!next);setMuted(next)};return <View style={s.wrap}><Card><Text style={s.h1}>Live Customer Call</Text><Text style={s.status}>{status}</Text><View style={s.row}><Button label={muted?'Unmute':'Mute'} secondary onPress={toggle}/><Button label="End Call" onPress={end}/></View></Card></View>}
const s=StyleSheet.create({wrap:{padding:18},h1:{fontSize:24,fontWeight:'900',color:theme.text,marginBottom:8},status:{color:theme.accent,fontWeight:'900',marginBottom:14},row:{flexDirection:'row',gap:10}});
