import React,{useEffect,useMemo,useState}from'react';
import {Alert,Linking,Modal,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,View}from'react-native';
import * as ImagePicker from'expo-image-picker';
import {GoogleSignin}from'@react-native-google-signin/google-signin';
import auth from'@react-native-firebase/auth';
import messaging from'@react-native-firebase/messaging';
import {Splash3D,theme,Card,Button,PressableScale,Pill,api,getToken,setToken,clearToken,upload}from'@commerce/mobile-core';
import PaymentEvidencePermission from'./src/PaymentEvidencePermission';
import CallPanel from'./src/CallPanel';
import {PaymentEvidenceNative} from'./src/nativePaymentEvidence';

const API=process.env.EXPO_PUBLIC_API_BASE_URL||(__DEV__?'http://10.0.2.2:4000':'');
if(!API) throw new Error('EXPO_PUBLIC_API_BASE_URL_REQUIRED');
if(!__DEV__ && !/^https:\/\//i.test(API)) throw new Error('PRODUCTION_API_MUST_USE_HTTPS');

type Order={id:string;name?:string;mobile_e164?:string;status:string;total_paise:number;payment_mode:string;payment_status:string;pickup_location_released_at?:string};

function useRealtime(onEvent:(e:any)=>void,enabled:boolean){
  useEffect(()=>{let ws:WebSocket|undefined;let closed=false;(async()=>{if(!enabled)return;const token=await getToken();if(!token)return;const url=API.replace(/^https?/,API.startsWith('https://')?'wss':'ws')+`/realtime?token=${encodeURIComponent(token)}`;ws=new WebSocket(url);ws.onmessage=e=>{try{onEvent(JSON.parse(e.data))}catch{}};ws.onerror=()=>{};ws.onclose=()=>{};})();return()=>{closed=true;if(ws&&ws.readyState===WebSocket.OPEN)ws.close();void closed}},[enabled,onEvent]);
}
GoogleSignin.configure({webClientId:process.env.EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID||undefined,iosClientId:process.env.EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID||undefined});

async function registerAdminPush(){try{const enabled=await messaging().hasPermission(); if(!enabled)return; const token=await messaging().getToken(); if(token) await api(API,'/v1/admin/devices',{method:'POST',body:JSON.stringify({fcmToken:token,platform:'ANDROID',notificationsEnabled:true})});}catch{}}

async function adminGoogleLogin(){
  const info=await GoogleSignin.signIn();
  const idToken=info.data?.idToken||info.data?.user?.idToken;
  if(!idToken)throw new Error('GOOGLE_ID_TOKEN_MISSING');
  const credential=auth.GoogleAuthProvider.credential(idToken);
  const result=await auth().signInWithCredential(credential);
  const firebaseToken=await result.user.getIdToken();
  const out=await api(API,'/v1/auth/admin/signin',{method:'POST',body:JSON.stringify({firebaseIdToken:firebaseToken})});
  await setToken(out.token); await registerAdminPush();
}
function Login({done}:{done:()=>void}){return <SafeAreaView style={s.root}><View style={s.login}><Text style={s.kicker}>PRIVATE DEALER CONSOLE</Text><Text style={s.h1}>Control the entire pickup system.</Text><Text style={s.muted}>Only the authorized dealer Gmail is accepted by the backend.</Text><Button label="Sign in with authorized Google account" onPress={async()=>{try{await adminGoogleLogin();done()}catch(e:any){Alert.alert('Admin sign-in',e?.message||'Access denied')}}}/></View></SafeAreaView>}

function Dashboard({go}:{go:(x:string)=>void}){
  const[incoming,setIncoming]=useState<any>(null);const[activeCall,setActiveCall]=useState<string|null>(null);const[orders,setOrders]=useState<Order[]>([]);
  const onEvent=React.useCallback((e:any)=>{if(e.type==='call.incoming')setIncoming(e);if(e.type==='call.ended'&&activeCall===e.callId)setActiveCall(null)},[activeCall]);
  useRealtime(onEvent,true);
  const load=()=>api(API,'/v1/admin/orders').then(x=>setOrders(x.orders)).catch(()=>{});useEffect(()=>{load();const t=setInterval(load,5000);return()=>clearInterval(t)},[]);
  const counts=useMemo(()=>orders.reduce((a,o)=>{a[o.status]=(a[o.status]||0)+1;return a},{} as any),[orders]);
  if(activeCall)return <ScrollView contentContainerStyle={s.body}><CallPanel callId={activeCall} onEnded={()=>setActiveCall(null)}/><Button label="Back to Dashboard" secondary onPress={()=>setActiveCall(null)}/></ScrollView>;
  return <ScrollView contentContainerStyle={s.body}>{incoming?<Card><Text style={s.h2}>Incoming customer call</Text><Text style={s.muted}>Customer {incoming.customerId}</Text><View style={s.row}><Button label="Accept" onPress={async()=>{try{await api(API,`/v1/admin/calls/${incoming.callId}/status`,{method:'POST',body:JSON.stringify({status:'ACTIVE'})});setActiveCall(incoming.callId);setIncoming(null)}catch(e:any){Alert.alert('Call',e.message)}}}/><Button label="Reject" secondary onPress={async()=>{try{await api(API,`/v1/admin/calls/${incoming.callId}/status`,{method:'POST',body:JSON.stringify({status:'REJECTED'})});setIncoming(null)}catch(e:any){Alert.alert('Call',e.message)}}}/></View></Card>:null}<Text style={s.kicker}>DEALER DASHBOARD</Text><Text style={s.h1}>Live operations.</Text><View style={s.grid}>{['PLACED','CONFIRMED','READY_FOR_PICKUP','PICKUP_VERIFICATION','PICKED_UP','COMPLETED'].map(x=><Card key={x} style={s.metric}><Text style={s.metricN}>{counts[x]||0}</Text><Text style={s.muted}>{x}</Text></Card>)}</View><Button label="Orders & Pickup" testID="DashboardOrders" onPress={()=>go('orders')}/><Button label="Payment Review" secondary onPress={()=>go('payments')}/><Button label="Products & Categories" secondary onPress={()=>go('products')}/><Button label="Customers & Chat" secondary onPress={()=>go('customers')}/><Button label="Calls" secondary onPress={()=>go('calls')}/><Button label="Notifications" secondary onPress={()=>go('broadcast')}/><Button label="UPI / Pickup / Tutorials" secondary onPress={()=>go('settings')}/></ScrollView>
}

function Products(){
  const[items,setItems]=useState<any[]>([]);const[categories,setCategories]=useState<any[]>([]);const[editingId,setEditingId]=useState<string|null>(null);const[name,setName]=useState('');const[desc,setDesc]=useState('');const[sku,setSku]=useState('');const[price,setPrice]=useState('');const[discount,setDiscount]=useState('');const[stock,setStock]=useState('');const[media,setMedia]=useState<any[]>([]);const[categoryId,setCategoryId]=useState('');const[newCategory,setNewCategory]=useState('');const[busy,setBusy]=useState(false);
  const load=()=>api(API,'/v1/admin/products').then(x=>setItems(x.products)).catch(()=>{});const loadCategories=()=>api(API,'/v1/categories').then(x=>setCategories(x.categories||[])).catch(()=>{});useEffect(()=>{load();loadCategories()},[]);
  const pickMedia=async()=>{try{const r=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images','videos'],quality:.88,selectionLimit:8});if(r.canceled)return;const out:any[]=[];for(const a of r.assets){const isVideo=(a.type||'').toLowerCase()==='video'||(a.mimeType||'').startsWith('video/');const mime=a.mimeType||(isVideo?'video/mp4':'image/jpeg');const ext=isVideo?'mp4':'jpg';const objectKey=await upload(API,await getToken()||'',a.uri,mime,ext);out.push({objectKey,kind:isVideo?'video':'image',name:a.fileName||(isVideo?'video':'image')});}setMedia(out)}catch(e:any){Alert.alert('Media upload',e.message)}};
  const fill=(p:any)=>{setEditingId(p.id);setName(p.name||'');setDesc(p.description||'');setSku(p.sku||'');setPrice((Number(p.price_paise)/100).toFixed(2));setDiscount((Number(p.discount_paise||0)/100).toFixed(2));setStock(String(p.stock_qty??0));setCategoryId(p.category_id||'');setMedia(Array.isArray(p.media_json)?p.media_json:[])};
  const reset=()=>{setEditingId(null);setName('');setDesc('');setSku('');setPrice('');setDiscount('');setStock('');setCategoryId('');setMedia([])};
  const save=async()=>{try{setBusy(true);const body={categoryId:categoryId||null,name,description:desc||null,sku:sku||null,pricePaise:Math.round(Number(price)*100),discountPaise:Math.round(Number(discount||0)*100),stockQty:Number(stock),mediaJson:media,published:true};if(editingId)await api(API,`/v1/admin/products/${editingId}`,{method:'PATCH',body:JSON.stringify(body)});else await api(API,'/v1/admin/products',{method:'POST',body:JSON.stringify(body)});reset();load()}catch(e:any){Alert.alert('Product',e.message)}finally{setBusy(false)}};
  const addCategory=async()=>{try{if(!newCategory.trim())return;await api(API,'/v1/admin/categories',{method:'POST',body:JSON.stringify({name:newCategory.trim()})});setNewCategory('');loadCategories()}catch(e:any){Alert.alert('Category',e.message)}};
  const toggle=async(p:any)=>{try{await api(API,`/v1/admin/products/${p.id}`,{method:'PATCH',body:JSON.stringify({published:!p.published})});load()}catch(e:any){Alert.alert('Product',e.message)}};
  const remove=async(p:any)=>{Alert.alert('Product',`Delete/archive ${p.name}?`,[{text:'Cancel',style:'cancel'},{text:'Continue',style:'destructive',onPress:async()=>{try{await api(API,`/v1/admin/products/${p.id}`,{method:'DELETE'});load()}catch(e:any){Alert.alert('Product',e.message)}}}])};
  return <ScrollView contentContainerStyle={s.body}><Text style={s.h1}>{editingId?'Edit product':'Products'}</Text><Text style={s.h2}>Category</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.chips}><PressableScale onPress={()=>setCategoryId('')} style={[s.chip,!categoryId&&s.chipActive]}><Text style={s.choiceText}>No category</Text></PressableScale>{categories.map(c=><PressableScale key={c.id} onPress={()=>setCategoryId(c.id)} style={[s.chip,categoryId===c.id&&s.chipActive]}><Text style={s.choiceText}>{c.name}</Text></PressableScale>)}</ScrollView><View style={s.row}><TextInput value={newCategory} onChangeText={setNewCategory} placeholder="New category" placeholderTextColor={theme.muted} style={[s.input,{flex:1}]}/><Button label="Add" secondary onPress={addCategory}/></View><TextInput value={name} onChangeText={setName} placeholder="Name" placeholderTextColor={theme.muted} style={s.input}/><TextInput value={sku} onChangeText={setSku} placeholder="SKU (optional)" placeholderTextColor={theme.muted} style={s.input}/><TextInput value={desc} onChangeText={setDesc} placeholder="Description" placeholderTextColor={theme.muted} style={[s.input,{minHeight:90}]}/><TextInput value={price} onChangeText={setPrice} keyboardType="decimal-pad" placeholder="Price ₹" placeholderTextColor={theme.muted} style={s.input}/><TextInput value={discount} onChangeText={setDiscount} keyboardType="decimal-pad" placeholder="Discount ₹" placeholderTextColor={theme.muted} style={s.input}/><TextInput value={stock} onChangeText={setStock} keyboardType="number-pad" placeholder="Stock" placeholderTextColor={theme.muted} style={s.input}/><Button label={media.length?`Media selected • ${media.length}`:'Add product photos'} secondary onPress={pickMedia}/><Button label={busy?(editingId?'Saving…':'Publishing…'):(editingId?'Save product':'Publish Product')} testID="PublishProductButton" onPress={save} disabled={busy||!name||!price||stock===''||Number(stock)<0||Number(price)<0}/>{editingId?<Button label="Cancel edit" secondary onPress={reset}/>:null}<Text style={s.h2}>Catalog</Text>{items.map(p=><Card key={p.id}><View style={s.row}><Text style={[s.h2,{flex:1}]}>{p.name}</Text><Pill active={p.published}>{p.published?'Published':'Hidden'}</Pill></View><Text style={s.muted}>{p.category||'Uncategorized'} • ₹{(Number(p.price_paise)/100).toFixed(2)} • stock {p.stock_qty}</Text><View style={s.row}><Button label="Edit" secondary onPress={()=>fill(p)}/><Button label={p.published?'Hide':'Publish'} secondary onPress={()=>toggle(p)}/><Button label="Delete" secondary onPress={()=>remove(p)}/></View></Card>)}</ScrollView>
}

function Payments(){
  const[orders,setOrders]=useState<Order[]>([]);const[permission,setPermission]=useState(false);const[result,setResult]=useState('');
  const load=()=>api(API,'/v1/admin/orders').then(x=>setOrders(x.orders.filter((o:Order)=>o.payment_mode==='UPI'&&o.payment_status==='SUBMITTED'))).catch(()=>{});useEffect(()=>{load();const t=setInterval(load,8000);return()=>clearInterval(t)},[]);
  const screenshot=async(o:Order)=>{try{const x=await api(API,`/v1/admin/payments/${o.id}/screenshot-url`);await Linking.openURL(x.url)}catch(e:any){Alert.alert('Screenshot',e.message)}};
  const verifyWithDevice=async(o:Order)=>{try{const device=await PaymentEvidenceNative.ensureKey();await api(API,'/v1/admin/payment-evidence/device/register',{method:'POST',body:JSON.stringify(device)});const evs=await PaymentEvidenceNative.collectEvidence();if(!evs.length){setResult('No payment SMS/UPI notification evidence was found on this dealer device.');return}let last='No matching trusted evidence';for(const ev of evs){const ch=await api(API,'/v1/admin/payment-evidence/device/challenge',{method:'POST'});const canonical={orderId:o.id,source:ev.source,utr:ev.utr,amountPaise:ev.amountPaise,payeeUpiId:ev.payeeUpiId||null,occurredAt:ev.occurredAt||null,rawReference:ev.rawReference||null,challenge:ch.nonce};const signature=await PaymentEvidenceNative.sign(JSON.stringify(canonical));try{const r=await api(API,`/v1/admin/payments/${o.id}/evidence`,{method:'POST',body:JSON.stringify({...canonical,challenge:undefined,deviceKeyId:device.keyId,challengeId:ch.challengeId,signatureBase64:signature})});last=r.verified?'Payment verified from trusted device evidence':'Evidence rejected';if(r.verified)break}catch(e:any){last=e.message}}setResult(last);load()}catch(e:any){setResult(e.message)}};
  const manual=async(o:Order,approve:boolean)=>{try{await api(API,`/v1/admin/payments/${o.id}/verify`,{method:'POST',body:JSON.stringify({approve,reason:approve?undefined:'Evidence could not be confirmed'})});load()}catch(e:any){Alert.alert('Payment',e.message)}};
  return <ScrollView contentContainerStyle={s.body}><Text style={s.h1}>Payment Verification</Text><Text style={s.muted}>Screenshot alone is never accepted. Dealer device evidence must be collected after explicit permission; matching checks UTR + amount + configured payee UPI when supplied.</Text><Button label={permission?'Evidence permission panel enabled':'Enable payment evidence permission'} onPress={()=>setPermission(true)}/>{result?<Card><Text style={s.text}>{result}</Text></Card>:null}{orders.length===0?<Card><Text style={s.muted}>No UPI payments waiting for verification.</Text></Card>:null}{orders.map(o=><Card key={o.id}><Text style={s.h2}>₹{(Number(o.total_paise)/100).toFixed(2)}</Text><Text style={s.muted}>{o.id}</Text><View style={s.row}><Button label="View screenshot" secondary onPress={()=>screenshot(o)}/><Button label="Check device" onPress={()=>verifyWithDevice(o)}/></View><View style={s.row}><Button label="Manual approve" secondary onPress={()=>manual(o,true)}/><Button label="Reject" secondary onPress={()=>manual(o,false)}/></View></Card>)}<Modal visible={permission} animationType="slide" onRequestClose={()=>setPermission(false)}><SafeAreaView style={s.root}><PaymentEvidencePermission/><Button label="Done" onPress={()=>setPermission(false)}/></SafeAreaView></Modal></ScrollView>
}

function Orders(){
  const[items,setItems]=useState<Order[]>([]);const[busy,setBusy]=useState(false);const load=()=>api(API,'/v1/admin/orders').then(x=>setItems(x.orders)).catch(()=>{});useEffect(()=>{load();const t=setInterval(load,6000);return()=>clearInterval(t)},[]);
  const transition=async(o:Order,next:string)=>{try{setBusy(true);const r=await api(API,`/v1/admin/orders/${o.id}/status`,{method:'PATCH',body:JSON.stringify({status:next})});if(r.verificationCode)Alert.alert('Pickup verification code',`Customer order: ${o.id}\nCode: ${r.verificationCode}\nExpires: ${new Date(r.order.pickup_verification_expires_at).toLocaleString()}`);load()}catch(e:any){Alert.alert('Order status',e.message)}finally{setBusy(false)}};
  const release=async(o:Order)=>{try{setBusy(true);await api(API,`/v1/admin/orders/${o.id}/release-pickup`,{method:'POST'});load()}catch(e:any){Alert.alert('Pickup release',e.message)}finally{setBusy(false)}};
  const codPaid=async(o:Order)=>{try{await api(API,`/v1/admin/orders/${o.id}/cod/mark-paid`,{method:'POST'});load()}catch(e:any){Alert.alert('COD',e.message)}};
  const location=async(o:Order)=>{try{const r=await api(API,`/v1/admin/orders/${o.id}/location/latest`);await Linking.openURL(`https://www.google.com/maps/search/?api=1&query=${r.location.latitude},${r.location.longitude}`)}catch(e:any){Alert.alert('Live location',e.message)}};
  return <ScrollView contentContainerStyle={s.body}><Text style={s.h1}>Orders & Pickup</Text>{items.map(o=><Card key={o.id}><View style={s.row}><Text style={[s.h2,{flex:1}]}>{o.name||o.mobile_e164||'Customer'}</Text><Pill active>{o.status}</Pill></View><Text style={s.muted}>₹{(Number(o.total_paise)/100).toFixed(2)} • {o.payment_mode} • {o.payment_status}</Text><View style={s.row}>{o.payment_mode==='COD'&&o.payment_status!=='VERIFIED'?<Button label="Mark COD Paid" secondary onPress={()=>codPaid(o)}/>:null}{['READY_FOR_PICKUP','PICKUP_VERIFICATION','PICKED_UP'].includes(o.status)?<Button label="Live location" secondary onPress={()=>location(o)}/>:null}{o.status==='CONFIRMED'?<Button label="Release Pickup" onPress={()=>release(o)}/>:null}{o.status==='READY_FOR_PICKUP'?<Button label="Start Verification" onPress={()=>transition(o,'PICKUP_VERIFICATION')}/>:null}{o.status==='CUSTOMER_COMPLETED'?<Button label="Finalize" onPress={()=>transition(o,'COMPLETED')}/>:null}{['PLACED','CONFIRMED'].includes(o.status)&&o.payment_status!=='VERIFIED'?<Button label="Cancel" secondary disabled={busy} onPress={()=>transition(o,'CANCELLED')}/>:null}</View></Card>)}</ScrollView>
}

function AdminChat(){const[items,setItems]=useState<any[]>([]);const[selected,setSelected]=useState<any>(null);const[text,setText]=useState('');const load=()=>api(API,'/v1/admin/conversations').then(x=>setItems(x.conversations)).catch(()=>{});useEffect(()=>{load();const t=setInterval(load,5000);return()=>clearInterval(t)},[]);const open=async(id:string)=>{try{const detail=await api(API,`/v1/admin/conversations/${id}`);setSelected(detail);await api(API,`/v1/conversations/${id}/read`,{method:'POST'});}catch(e:any){Alert.alert('Chat',e.message)}};const send=async()=>{if(!selected||!text.trim())return;try{await api(API,`/v1/admin/conversations/${selected.conversation.id}/message`,{method:'POST',body:JSON.stringify({body:text})});setText('');open(selected.conversation.id)}catch(e:any){Alert.alert('Chat',e.message)}};const takeover=async()=>{if(!selected)return;try{await api(API,`/v1/admin/conversations/${selected.conversation.id}/takeover`,{method:'POST',body:JSON.stringify({reason:'Dealer human support'})});open(selected.conversation.id)}catch(e:any){Alert.alert('Chat',e.message)}};const returnAI=async()=>{if(!selected)return;try{await api(API,`/v1/admin/conversations/${selected.conversation.id}/return-to-ai`,{method:'POST'});open(selected.conversation.id)}catch(e:any){Alert.alert('Chat',e.message)}};if(selected)return <ScrollView contentContainerStyle={s.body}><Text style={s.h1}>Customer Chat</Text><View style={s.row}><Pill active>{selected.conversation.assigned_to}</Pill><Button label="Take Over" onPress={takeover}/><Button label="Return AI" secondary onPress={returnAI}/></View>{selected.messages.map((m:any)=><Card key={m.id}><Text style={s.muted}>{m.sender_type}</Text><Text style={s.text}>{m.body}</Text></Card>)}{selected.conversation.assigned_to==='ADMIN'?<View style={s.row}><TextInput value={text} onChangeText={setText} placeholder="Reply" placeholderTextColor={theme.muted} style={[s.input,{flex:1}]}/><Button label="Send" onPress={send}/></View>:null}<Button label="Back" secondary onPress={()=>setSelected(null)}/></ScrollView>;return <ScrollView contentContainerStyle={s.body}><Text style={s.h1}>Customers & Chat</Text>{items.map(c=><PressableScale key={c.id} onPress={()=>open(c.id)}><Card><View style={s.row}><Text style={[s.h2,{flex:1}]}>{c.name||c.mobile_e164}</Text><Pill active>{c.online?'ONLINE':c.last_seen_at?'RECENT':'OFFLINE'}</Pill></View><Text style={s.muted}>{c.assigned_to} • unread {c.unread_customer_messages||0}</Text><Text style={s.text} numberOfLines={2}>{c.last_message||'No messages yet.'}</Text></Card></PressableScale>)}</ScrollView>}

function AdminCalls(){const[items,setItems]=useState<any[]>([]);const[selected,setSelected]=useState<any>(null);const load=()=>api(API,'/v1/admin/calls').then(x=>setItems(x.calls)).catch(()=>{});useEffect(()=>{load();const t=setInterval(load,8000);return()=>clearInterval(t)},[]);const detail=async(id:string)=>{try{const x=await api(API,`/v1/admin/calls/${id}`);setSelected(x.call)}catch(e:any){Alert.alert('Call',e.message)}};return <ScrollView contentContainerStyle={s.body}><Text style={s.h1}>Calls</Text>{selected?<><Card><Text style={s.h2}>{selected.name||'Customer'}</Text><Text style={s.muted}>{selected.mobile_e164||''} • {selected.status}</Text><Text style={s.text}>{selected.transcript||'Transcript not available yet.'}</Text>{selected.recording_object_key?<Button label="Open protected recording" onPress={async()=>{try{const x=await api(API,`/v1/admin/calls/${selected.id}/recording-url`);await Linking.openURL(x.url)}catch(e:any){Alert.alert('Recording',e.message)}}}/>:null}</Card><Button label="Back" secondary onPress={()=>setSelected(null)}/></>:items.map(c=><PressableScale key={c.id} onPress={()=>detail(c.id)}><Card><View style={s.row}><Text style={s.h2}>{c.name||'Customer'}</Text><Pill active>{c.status}</Pill></View><Text style={s.muted}>{c.mode} • {new Date(c.created_at).toLocaleString()}</Text></Card></PressableScale>)}</ScrollView>}

function Settings(){
  const[upi,setUpi]=useState('');const[next,setNext]=useState<string|null>(null);const[key,setKey]=useState('');const[req,setReq]=useState<string|null>(null);const[tutorial,setTutorial]=useState('');const[adminTutorial,setAdminTutorial]=useState('');const[pickup,setPickup]=useState<any>(null);const[pickupText,setPickupText]=useState('');const[lat,setLat]=useState('');const[lon,setLon]=useState('');const[videoKey,setVideoKey]=useState('');const[upiEnabled,setUpiEnabled]=useState(true);const[codEnabled,setCodEnabled]=useState(true);const[busy,setBusy]=useState(false);
  const load=async()=>{try{const x=await api(API,'/v1/admin/payment-settings');setUpi(x.upiId||'');setNext(x.nextFreeChangeAt)}catch{}try{const x=await api(API,'/v1/admin/pickup-settings');const p=x.pickup;setPickup(p);setPickupText(p?.location_text||'');setLat(p?.latitude!=null?String(p.latitude):'');setLon(p?.longitude!=null?String(p.longitude):'');setVideoKey(p?.video_object_key||'')}catch{}try{const x=await api(API,'/v1/admin/payment-modes');setUpiEnabled(!!x.upiEnabled);setCodEnabled(!!x.codEnabled)}catch{}};useEffect(()=>{load()},[]);
  const change=async()=>{try{const r=await api(API,'/v1/admin/payment-settings/upi/change',{method:'POST',body:JSON.stringify({upiId:upi})});if(r.unlockRequired){setReq(r.requestId);Alert.alert('Early change','90-day window is active. ₹799 policy applies; get the developer unlock key.')}else{Alert.alert('UPI','Updated');load()}}catch(e:any){Alert.alert('UPI',e.message)}};
  const unlock=async()=>{if(!req)return;try{await api(API,`/v1/admin/payment-settings/upi/change/${req}/unlock`,{method:'POST',headers:{'X-Developer-Early-UPI-Key':key}});Alert.alert('UPI','Early change unlocked');setKey('');setReq(null);load()}catch(e:any){Alert.alert('UPI unlock',e.message)}};
  const saveModes=async()=>{if(!upiEnabled&&!codEnabled){Alert.alert('Payment modes','At least one mode must remain enabled.');return}try{await api(API,'/v1/admin/payment-modes',{method:'POST',body:JSON.stringify({upiEnabled,codEnabled})});Alert.alert('Payment modes','Updated')}catch(e:any){Alert.alert('Payment modes',e.message)}};
  const savePickup=async()=>{try{setBusy(true);const r=await api(API,'/v1/admin/pickup-settings',{method:'POST',body:JSON.stringify({locationText:pickupText||null,latitude:lat===''?null:Number(lat),longitude:lon===''?null:Number(lon),videoObjectKey:videoKey||null})});setPickup(r.pickup);Alert.alert('Pickup','Settings saved')}catch(e:any){Alert.alert('Pickup',e.message)}finally{setBusy(false)}};
  const pickVideo=async()=>{try{const r=await ImagePicker.launchImageLibraryAsync({mediaTypes:['videos'],quality:.8});if(r.canceled)return;const a=r.assets[0];setVideoKey(await upload(API,await getToken()||'',a.uri,a.mimeType||'video/mp4','mp4'));Alert.alert('Video','Uploaded')}catch(e:any){Alert.alert('Video upload',e.message)}};
  const saveTutorial=async(aud:'CUSTOMER'|'ADMIN',url:string)=>{try{await api(API,'/v1/admin/tutorials',{method:'POST',body:JSON.stringify({audience:aud,title:aud==='CUSTOMER'?'How to use app':'Dealer guide',videoUrl:url})});Alert.alert('Tutorial','Updated')}catch(e:any){Alert.alert('Tutorial',e.message)}};
  return <ScrollView contentContainerStyle={s.body}><Text style={s.h1}>Settings</Text><AdminTutorialGate/><Text style={s.h2}>Dealer UPI</Text><TextInput value={upi} onChangeText={setUpi} autoCapitalize="none" placeholder="dealer@upi" placeholderTextColor={theme.muted} style={s.input}/>{next?<Text style={s.muted}>Next free change: {new Date(next).toLocaleString()}</Text>:<Text style={s.muted}>First UPI setup is free.</Text>}<Button label="Save UPI" onPress={change}/>{req?<Card><Text style={s.h2}>Early change — ₹799</Text><Text style={s.muted}>This is not a customer-payment transaction. Developer unlock key required.</Text><TextInput value={key} onChangeText={setKey} secureTextEntry autoCapitalize="none" style={s.input}/><Button label="Unlock Early Change" onPress={unlock}/></Card>:null}<Text style={s.h2}>Payment modes</Text><View style={s.row}><PressableScale onPress={()=>setUpiEnabled(x=>!x)} style={[s.chip,upiEnabled&&s.chipActive]}><Text style={s.choiceText}>UPI {upiEnabled?'ON':'OFF'}</Text></PressableScale><PressableScale onPress={()=>setCodEnabled(x=>!x)} style={[s.chip,codEnabled&&s.chipActive]}><Text style={s.choiceText}>COD {codEnabled?'ON':'OFF'}</Text></PressableScale><Button label="Save" secondary onPress={saveModes}/></View><Text style={s.h2}>Pickup point</Text><TextInput value={pickupText} onChangeText={setPickupText} placeholder="Pickup address/instructions" placeholderTextColor={theme.muted} style={[s.input,{minHeight:80}]}/><View style={s.row}><TextInput value={lat} onChangeText={setLat} keyboardType="decimal-pad" placeholder="Latitude" placeholderTextColor={theme.muted} style={[s.input,{flex:1}]}/><TextInput value={lon} onChangeText={setLon} keyboardType="decimal-pad" placeholder="Longitude" placeholderTextColor={theme.muted} style={[s.input,{flex:1}]}/></View><Button label={videoKey?'Replace pickup instruction video':'Upload pickup instruction video'} secondary onPress={pickVideo}/><Button label={busy?'Saving…':'Save pickup settings'} testID="PickupControls" onPress={savePickup}/><AiCampaignSettings/><Text style={s.h2}>Tutorials</Text><TextInput value={tutorial} onChangeText={setTutorial} placeholder="Customer tutorial video URL" placeholderTextColor={theme.muted} style={s.input}/><Button label="Save customer tutorial" secondary onPress={()=>saveTutorial('CUSTOMER',tutorial)}/><TextInput value={adminTutorial} onChangeText={setAdminTutorial} placeholder="Admin tutorial video URL" placeholderTextColor={theme.muted} style={s.input}/><Button label="Save admin tutorial" secondary onPress={()=>saveTutorial('ADMIN',adminTutorial)}/></ScrollView>;
}


function AdminTutorialGate(){const[tutorial,setTutorial]=useState<any>(null);const[open,setOpen]=useState(false);useEffect(()=>{api(API,'/v1/tutorials/ADMIN').then((x:any)=>setTutorial(x.tutorial)).catch(()=>{})},[]);if(!tutorial)return null;return <><Button label="How to use" secondary onPress={()=>setOpen(true)}/><Modal visible={open} animationType="slide" onRequestClose={()=>setOpen(false)}><SafeAreaView style={s.root}><ScrollView contentContainerStyle={s.body}><Text style={s.h1}>{tutorial.title||'Dealer guide'}</Text>{tutorial.voiceExplanation?<Text style={s.text}>{tutorial.voiceExplanation}</Text>:null}{tutorial.videoUrl?<Button label="Watch tutorial" onPress={()=>Linking.openURL(tutorial.videoUrl)}/>:null}<Button label="Close" secondary onPress={()=>setOpen(false)}/></ScrollView></SafeAreaView></Modal></>}
function AiCampaignSettings(){const[enabled,setEnabled]=useState(false);const[days,setDays]=useState(3);const[last,setLast]=useState<string|null>(null);const[busy,setBusy]=useState(false);useEffect(()=>{api(API,'/v1/admin/ai-campaign-settings').then((r:any)=>{setEnabled(!!r.enabled);setDays(Number(r.intervalDays)||3);setLast(r.lastSentAt||null)}).catch(()=>{})},[]);const save=async()=>{try{setBusy(true);const r=await api(API,'/v1/admin/ai-campaign-settings',{method:'POST',body:JSON.stringify({enabled,intervalDays:days})});setLast(r.lastSentAt||null);Alert.alert('AI notifications','Settings saved. Scheduler runs every 3–4 days when AI + FCM are configured.')}catch(e:any){Alert.alert('AI notifications',e.message)}finally{setBusy(false)}};return <Card><Text style={s.h2}>AI new-product notifications</Text><Text style={s.muted}>Only opted-in customers receive these. Content uses the latest published product.</Text><View style={s.row}><PressableScale onPress={()=>setEnabled(x=>!x)} style={[s.chip,enabled&&s.chipActive]}><Text style={s.choiceText}>{enabled?'ON':'OFF'}</Text></PressableScale><PressableScale onPress={()=>setDays(d=>d===3?4:3)} style={s.chip}><Text style={s.choiceText}>{days} days</Text></PressableScale><Button label={busy?'Saving…':'Save'} secondary onPress={save}/></View>{last?<Text style={s.muted}>Last sent: {new Date(last).toLocaleString()}</Text>:null}</Card>}
function AuditLogs(){const[logs,setLogs]=useState<any[]>([]);useEffect(()=>{api(API,'/v1/admin/audit-logs?limit=100').then((r:any)=>setLogs(r.logs||[])).catch(()=>{})},[]);return <ScrollView contentContainerStyle={s.body}><Text style={s.h1}>Audit & Security Logs</Text>{logs.length===0?<Text style={s.muted}>No logs available.</Text>:logs.map(l=><Card key={l.id}><Text style={s.h2}>{l.action}</Text><Text style={s.muted}>{l.actor_type} • {l.entity_type||'system'} • {l.created_at?new Date(l.created_at).toLocaleString():''}</Text><Text style={s.text}>{JSON.stringify(l.metadata||{})}</Text></Card>)}</ScrollView>}

function AdminAI(){const[q,setQ]=useState('');const[answer,setAnswer]=useState('');const[busy,setBusy]=useState(false);const ask=async()=>{if(!q.trim())return;try{setBusy(true);const r=await api(API,'/v1/admin/assistant',{method:'POST',body:JSON.stringify({body:q})});setAnswer(r.answer)}catch(e:any){Alert.alert('AI Assistant',e.message)}finally{setBusy(false)}};return <ScrollView contentContainerStyle={s.body}><Text style={s.h1}>AI Assistant</Text><Text style={s.muted}>Operational help grounded in current backend data. AI does not invent unavailable facts.</Text><TextInput value={q} onChangeText={setQ} placeholder="Ask about orders, stock, customers…" placeholderTextColor={theme.muted} style={[s.input,{minHeight:90}]}/><Button label={busy?'Thinking…':'Ask AI'} onPress={ask} disabled={busy||!q.trim()}/>{answer?<Card><Text style={s.muted}>AI</Text><Text style={s.text}>{answer}</Text></Card>:null}</ScrollView>}
function Broadcast(){const[title,setTitle]=useState('');const[body,setBody]=useState('');const[marketing,setMarketing]=useState(false);const send=async()=>{try{const r=await api(API,'/v1/admin/notifications/broadcast',{method:'POST',body:JSON.stringify({title,body,marketing})});Alert.alert('Broadcast',`Sent ${r.sent}/${r.eligibleDevices}`);setTitle('');setBody('')}catch(e:any){Alert.alert('Broadcast',e.message)}};return <ScrollView contentContainerStyle={s.body}><Text style={s.h1}>Broadcast</Text><TextInput value={title} onChangeText={setTitle} placeholder="Title" placeholderTextColor={theme.muted} style={s.input}/><TextInput value={body} onChangeText={setBody} placeholder="Message" placeholderTextColor={theme.muted} style={[s.input,{minHeight:110}]}/><PressableScale onPress={()=>setMarketing(x=>!x)} style={[s.chip,marketing&&s.chipActive]}><Text style={s.choiceText}>{marketing?'Marketing permission required':'Operational notification'}</Text></PressableScale><Button label="Send broadcast" onPress={send} disabled={!title.trim()||!body.trim()}/></ScrollView>}

export default function App(){const[boot,setBoot]=useState(false);const[authed,setAuthed]=useState(false);const[checking,setChecking]=useState(true);const[tab,setTab]=useState('dashboard');
  useEffect(()=>{let alive=true;(async()=>{try{const t=await getToken();if(!t){if(alive)setAuthed(false);return}const session=await api(API,'/v1/auth/session');if(session?.active&&session.role==='ADMIN'){if(alive)setAuthed(true)}else{await clearToken();if(alive)setAuthed(false)}}catch{await clearToken();if(alive)setAuthed(false)}finally{if(alive)setChecking(false)}})();return()=>{alive=false}},[]);
  const logout=async()=>{try{await api(API,'/v1/auth/logout',{method:'POST'})}catch{}try{await auth().signOut()}catch{}await clearToken();setAuthed(false);setTab('dashboard')};
  if(!boot)return <Splash3D title="Dealer Console" onDone={()=>setBoot(true)}/>;if(checking)return <SafeAreaView style={s.root}><View style={s.login}><Text style={s.kicker}>SECURE SESSION</Text><Text style={s.h1}>Checking dealer access…</Text><Text style={s.muted}>Your server session is being verified before the console opens.</Text></View></SafeAreaView>;if(!authed)return <Login done={()=>setAuthed(true)}/>;let content:any=<Dashboard go={setTab}/>;if(tab==='products')content=<Products/>;if(tab==='payments')content=<Payments/>;if(tab==='orders')content=<Orders/>;if(tab==='broadcast')content=<Broadcast/>;if(tab==='settings')content=<Settings/>;if(tab==='customers')content=<AdminChat/>;if(tab==='calls')content=<AdminCalls/>;if(tab==='ai')content=<AdminAI/>;if(tab==='audit')content=<AuditLogs/>;return <SafeAreaView style={s.root}>{content}<View style={s.nav}><PressableScale testID="DashboardTab" onPress={()=>setTab('dashboard')} style={s.navItem}><Text style={s.navText}>Dashboard</Text></PressableScale><PressableScale testID="ProductsTab" onPress={()=>setTab('products')} style={s.navItem}><Text style={s.navText}>Products</Text></PressableScale><PressableScale testID="OrdersTab" onPress={()=>setTab('orders')} style={s.navItem}><Text style={s.navText}>Orders</Text></PressableScale><PressableScale testID="ConversationsTab" onPress={()=>setTab('customers')} style={s.navItem}><Text style={s.navText}>Chat</Text></PressableScale><PressableScale testID="SettingsTab" onPress={()=>setTab('settings')} style={s.navItem}><Text style={s.navText}>Settings</Text></PressableScale><PressableScale onPress={()=>setTab('ai')} style={s.navItem}><Text style={s.navText}>AI</Text></PressableScale><PressableScale onPress={()=>setTab('audit')} style={s.navItem}><Text style={s.navText}>Audit</Text></PressableScale><PressableScale onPress={logout} style={s.navItem}><Text style={s.navText}>Logout</Text></PressableScale></View></SafeAreaView>}

const s=StyleSheet.create({root:{flex:1,backgroundColor:theme.bg},body:{flexGrow:1,padding:18,gap:12},login:{flex:1,padding:20,justifyContent:'center',gap:14},kicker:{fontSize:11,fontWeight:'900',letterSpacing:1.6,color:theme.muted},h1:{fontSize:32,fontWeight:'900',color:theme.text,marginBottom:8},h2:{fontSize:18,fontWeight:'900',color:theme.text},muted:{color:theme.muted,lineHeight:20},text:{color:theme.text,lineHeight:22},input:{minHeight:50,borderWidth:1,borderColor:theme.border,borderRadius:16,paddingHorizontal:14,color:theme.text,backgroundColor:theme.surface2},grid:{flexDirection:'row',flexWrap:'wrap',gap:10},metric:{width:'47%',gap:4},metricN:{fontSize:30,fontWeight:'900',color:theme.accent},nav:{flexDirection:'row',gap:4,padding:6,borderTopWidth:1,borderTopColor:theme.border,backgroundColor:theme.surface},navItem:{flex:1,padding:10,alignItems:'center'},navText:{color:theme.text,fontSize:10,fontWeight:'900'},row:{flexDirection:'row',alignItems:'center',gap:10},chips:{gap:8},chip:{paddingHorizontal:14,paddingVertical:10,borderWidth:1,borderColor:theme.border,borderRadius:18},chipActive:{borderColor:theme.accent,backgroundColor:'rgba(110,242,178,.12)'},choiceText:{color:theme.text,fontWeight:'900'}});
