apply plugin: 'com.android.library'
apply plugin: 'org.jetbrains.kotlin.android'

android {
  namespace 'com.commerce.paydetection'
  compileSdkVersion rootProject.ext.compileSdkVersion
  defaultConfig { minSdkVersion rootProject.ext.minSdkVersion }
}

dependencies { implementation project(':expo-modules-core') }
